/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KeywordQuery struct {
	// The optional source selection id for the search query (mi only)
	SourceSelectionId int64      `json:"source_selection_id,omitempty"`
	FilterSet         *FilterSet `json:"filter_set,omitempty"`
	// None of these keywords should match
	NotKeywords []string `json:"not_keywords"`
	// At least one of these keywords must match
	AnyKeywords []string `json:"any_keywords"`
	// All of these keywords must match
	AllKeywords []string `json:"all_keywords"`
}
