/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OneOfQuery struct {
	Type            string `json:"type"`
	CaseSensitivity string `json:"case_sensitivity,omitempty"`

	BooleanQuery
	KeywordQuery
	CombinedQuery
}
