/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Company
type Company struct {
	// Company name
	Name string `json:"name"`
	// Company unique identifier
	Id string `json:"id"`
}
