/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// TopEntitiesResponse
type TopEntitiesResponse struct {
	DocumentCount int64 `json:"document_count"`
	Entities []Entity `json:"entities"`
}
