/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SearchDetails struct {
	// Search name
	Name string `json:"name"`
	// Search id
	Id int32 `json:"id"`
}
