/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Shares
type Shares struct {
	Retweets int64 `json:"retweets,omitempty"`
	Likes int64 `json:"likes,omitempty"`
}
