/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Sentiments
type Sentiments struct {
	Positive *SentimentStats `json:"positive"`
	Negative *SentimentStats `json:"negative"`
	Neutral *SentimentStats `json:"neutral"`
	Unknown *SentimentStats `json:"unknown"`
}
