/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Twitter
type Twitter struct {
	Followers int64 `json:"followers,omitempty"`
	Following int64 `json:"following,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
}
