/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Search
type SearchV2 struct {
	// The type of content that the search is for
	Type_ string `json:"type"`
	Category string `json:"category"`
	// UTC date time (in ISO-8601 format) when the search was last updated
	Updated time.Time `json:"updated,omitempty"`
	// Identifier
	Id int64 `json:"id"`
	// Search name
	Name string `json:"name"`
	Query *Query `json:"query,omitempty"`
	// DEPRECATED. Use \"id\" instead.
	SearchId int64 `json:"search_id,omitempty"`
}
