/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ServiceUnavailable
type AnalyticsServiceUnavailable struct {
	// List of problems with the request
	Errors []ErrorDetails `json:"errors,omitempty"`
	Type_ string `json:"type"`
	Message string `json:"message,omitempty"`
}
