/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CombinedQuery struct {
	// The optional source selection id for the search query (mi only)
	SourceSelectionId int64 `json:"source_selection_id,omitempty"`
	FilterSet *FilterSet `json:"filter_set,omitempty"`
	// None of these searches should match
	NotSearches []int64 `json:"not_searches,omitempty"`
	// At least one of these searches must match
	AnySearches []int64 `json:"any_searches,omitempty"`
	// All of these searches must match
	AllSearches []int64 `json:"all_searches,omitempty"`
}
