/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Author
type Author struct {
	Username string `json:"username,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Twitter *Twitter `json:"twitter,omitempty"`
	AvatarUrl string `json:"avatar_url,omitempty"`
	Authority int64 `json:"authority,omitempty"`
}
