/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// One-time export Response
type OneTimeExportResponse struct {
	OnetimeExport *OneTimeExportResult `json:"onetime_export"`
}
