/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Source Selection
type SourceSelection struct {
	// The type of searches this source selection can be used for
	Type_ string `json:"type"`
	// Source selection name
	Name string `json:"name"`
	// Source selection unique identifier
	Id int64 `json:"id"`
	// If this source selection is a custom one or not
	Custom bool `json:"custom"`
}
