/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// POST body for creating a one-time export
type OneTimeExportRequest struct {
	OnetimeExport *OneTimeExport `json:"onetime_export,omitempty"`
}
