/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// LanguageStats
type LanguageStats struct {
	LanguageCode string `json:"language_code"`
	DocumentCount int64 `json:"document_count"`
	Percentage float64 `json:"percentage"`
}
