/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Unauthorized struct {
	// A message describing, in brief, the problem.
	Message string `json:"message"`
	// A breakdown of each problem encountered, by field.
	Errors map[string][]string `json:"errors"`
}
