/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Search
type SearchRequestV2 struct {
	// The type of content that the search is for
	Type_ string `json:"type"`
	// The name associated with this search
	Name string `json:"name"`
	Query *Query `json:"query"`
	// The category of search to create this under, defaults to `mi`
	Category string `json:"category,omitempty"`
	// Identifier
	Id int32 `json:"id,omitempty"`
}
