/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Volume
type Volume struct {
	DocumentCount int64 `json:"document_count"`
	PerDay int64 `json:"per_day,omitempty"`
	PerHour int64 `json:"per_hour,omitempty"`
}
