/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SavedFilterSet struct {
	// ID number for the Saved Filter Set
	Id int64 `json:"id"`
	// Name of the Saved Filter Set, is optional when referencing one
	Name string `json:"name,omitempty"`
	// Type of Saved Filter Set, may be CUSTOM for user-created or QUICKPICK for meltwater-created, is optional when referencing one
	Subtype string `json:"subtype,omitempty"`
}
