/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// TopSharedResponse
type TopSharedResponse struct {
	DocumentCount int64 `json:"document_count"`
	Results []Document `json:"results"`
}
