/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Hour
type Hour struct {
	// An ISO8601 date-time, including timezone offset.  The timezone offset is an offset in minutes from UTC.
	Timestamp time.Time `json:"timestamp"`
	DocumentCount int64 `json:"document_count"`
}
