/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CountryStats
type CountryStats struct {
	CountryCode string `json:"country_code"`
	DocumentCount int64 `json:"document_count"`
	Percentage float64 `json:"percentage"`
}
