/*
 * Meltwater API
 *
 * The Meltwater Public API
 *
 * API version: 1.0
 * Contact: support@api.meltwater.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Document
type Document struct {
	Author *Author `json:"author"`
	Url string `json:"url,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Shares *Shares `json:"shares"`
	LanguageCode string `json:"language_code,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	// An ISO8601 date-time, including timezone offset.  The timezone offset is an offset in minutes from UTC.
	CreatedAt time.Time `json:"created_at,omitempty"`
}
